services:
  # Backend Service
  - type: web
    name: internship-backend
    env: docker
    repo: https://github.com/Reilla250/National_internship.git
    rootDir: backend/internship-backend
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 8085
      - key: DB_HOST
        value: jdbc:mysql://shortline.proxy.rlwy.net:44641/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: zkJyVvwSZXIhtygFYXSBYC1KOIkrGPRX
      - key: DB_NAME
        value: railway
